config/routes.rb
Rails.application.routes.draw do

  root 'static_pages#home'
  get    '/help',    to: 'static_pages#help'
  get    '/about',   to: 'static_pages#about'
  get    '/contact', to: 'static_pages#contact'
  get    '/signup',  to: 'users#new'
  get    '/login',   to: 'sessions#new'
  get 'auth/:provider/callback', to: 'sessions#create'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'
  resources :users do
    member do
      get :following, :followers
    end
  end
  resources :account_activations, only: [:edit]
  resources :password_resets,     only: [:new, :create, :edit, :update]
  resources :microposts,          only: [:create, :destroy]
  resources :relationships,       only: [:create, :destroy]
  resources :notifications, only: :index
  resources :likes, only: [:create, :destroy]
end

app/models/notification.rb
class Notification < ApplicationRecord
  default_scope->{order(created_at: :desc)}
  belongs_to :micropost, optional: true
end

app/controllers/notifications_controller.rb
class NotificationsController < ApplicationController
  def index
    @notifications=current_user.passive_notifications.page(params[:page])
    @notifications.where(checked: false).each do |notification|
      notification.update_attributes(checked: true)
    end
  end
end

app/helpers/notifications_helper.rb
module NotificationsHelper
  
  def unchecked_notifications
    @notifications=current_user.passive_notifications.where(checked: false)
  end
    
  def notification_form(notification)
    @comment=nil
    visiter=link_to notification.visiter.name, notification.visiter, style:"font-weight: bold;"
    your_post=link_to 'あなたの投稿', notification.micropost, style:"font-weight: bold;", remote: true
    case notification.action
      when "follow" then
        "#{visiter}があなたをフォローしました"
      when "like" then
        "#{visiter}が#{your_post}にいいね！しました"
      when "comment" then
        @comment=Comment.find_by(id:notification.comment_id)&.content
        "#{visiter}が#{your_post}にコメントしました"
    end
  end
end

app/views/notifications/_notification.html.erb
<% visiter=notification.visiter %>
<% post=notification.micropost %>

<div class="user-view clearfix ">
  <%= link_to user_path(notification.visiter) do %>
    <%=  image_tag notification.visiter.image[:small].url, class:"user-thumb", style:"width: 60px;"%>
  <% end %>
  <%== notification_form(notification) %><span class="moderate-font"><%= " (#{time_ago_in_words(notification.created_at)}前)" %></span>
  <br>
  <% if !@comment.nil? %>
    <p class="moderate-font"><%= @comment %></p>
  <% end %>
</div>

app/views/notifications/index.html.erb
<% provide(:title, 'Notification') %>

<div>
  <h4 class="sub-title">通知</h4>
  <% if @notifications.exists? %>
    <div class="users-index">
      <%= render   @notifications %>
      <%= paginate @notifications %>
    </div>
  <% else %>
    <p>通知はありません</p>
  <% end %>
</div>